version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banking_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - banking_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    environment:
      REDIS_PASSWORD: password
    command: [ "redis-server", "--requirepass", "password" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - banking_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - banking_network

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:


networks:
  banking_network:
    driver: bridge
